// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFOFZ1x-wRfOm3Maj0xi821nsZby9b6Fo',
    appId: '1:654126016153:web:5f0409b24ff36c6c2b7a08',
    messagingSenderId: '654126016153',
    projectId: 'example-ae85e',
    authDomain: 'example-ae85e.firebaseapp.com',
    storageBucket: 'example-ae85e.firebasestorage.app',
    measurementId: 'G-0G8JV679P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1fQ29KOKOxUZkXOC-YIMHVcRYMEgZAH4',
    appId: '1:654126016153:android:b1b2353d2d6fa5ad2b7a08',
    messagingSenderId: '654126016153',
    projectId: 'example-ae85e',
    storageBucket: 'example-ae85e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP9UthJNLorBYUXL1dGSSfiQWm42k-pS0',
    appId: '1:654126016153:ios:077078f2930f13fe2b7a08',
    messagingSenderId: '654126016153',
    projectId: 'example-ae85e',
    storageBucket: 'example-ae85e.firebasestorage.app',
    iosBundleId: 'com.example.freecodecamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP9UthJNLorBYUXL1dGSSfiQWm42k-pS0',
    appId: '1:654126016153:ios:077078f2930f13fe2b7a08',
    messagingSenderId: '654126016153',
    projectId: 'example-ae85e',
    storageBucket: 'example-ae85e.firebasestorage.app',
    iosBundleId: 'com.example.freecodecamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFOFZ1x-wRfOm3Maj0xi821nsZby9b6Fo',
    appId: '1:654126016153:web:1cbd9a3a266794b12b7a08',
    messagingSenderId: '654126016153',
    projectId: 'example-ae85e',
    authDomain: 'example-ae85e.firebaseapp.com',
    storageBucket: 'example-ae85e.firebasestorage.app',
    measurementId: 'G-NWC3RN11TV',
  );
}
